language: python
sudo: false
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  allow_failures:
    python: "nightly"

cache: pip
before_install:
  - rm -rf dist && python setup.py sdist # prep package distribution
install:
  - pip install dist/*.tar.gz # install dependencies as specified in setup.py
  - pip install -r test_requirements.txt
script:
  - pytest
after_success:
  - coveralls
